export const images = {
  image_1: require('./1.png'),
  image_2: require('./2.png'),
  image_3: require('./3.png'),
  image_4: require('./cttn.png'),
  image_5: require('./cttt.png'),
  image_6: require('./mtk.png'),
  image_7: require('./mtk1.png'),
  image_8: require('./qln.png'),
  image_9: require('./qln1.png'),
  image_10: require('./cttn1.png'),
  image_11: require('./backgr.jpeg'),
  image_12: require('./blue.jpeg'),
  image_13: require('./bottom4.jpeg'),
  image_14: require('./bieudo.png'),
  image_15: require('./visa.png'),
  image_16: require('./vcbRewards.png'),
  image_17: require('./update.png'),
  image_18: require('./q.png'),
  image_19: require('./w.png'),
  image_20: require('./y.png'),
  image_21: require('./t.png'),
  image_22: require('./tt.png'),
  image_23: require('./ttt.png'),
  image_24: require('./tttt.png'),
  image_25: require('./t5.png'),
};
